language: java
jdk: oraclejdk11
install: mvn -q dependency:resolve
cache:
  directories:
  - "$HOME/bin"
  - "$HOME/.m2"
notifications:
  slack:
    secure: oh0edh1Gh12FadPwqelbRU9z76kJZY4K7zCohxKEW2KjSP48ZnD7cAXHBzwX8d86GMkLc6RpEmd8jAfkn5IxQukQCBdqOjjsg/FimmJR8HnnCy2SaJ1wY0B6b1DJexesJz4YPb6+cxn8TNNJ1fBVVnP/x4Tv4GIPbaVOwbOG9rUJwq12u3D8CI/oN88LR4YX+26sB5POBxccA3BuLUYoGd9GbOaBOBy/TYAw/ECjI3t2JLDVNoQtCtd+oiwnGsDF57vDA7sPPJWFvbXEb++5qrt02atPgVgTz17CNpv/qZ8mT/LveDtBGYkiwXRElCoLRX0gqW4MSyiNsbVyrShGW1u0sCJktMuoqxf2UcJNhrJxCcUt3FBitXg7tSB1Rnlm6xf8mhpGNeq/LBYVuolcZe7xSO/lmns1CSQ1KszmcZ4jDMtsH2lsrbo8odW/FkSWuFdsKp8t0EDIYHrgawtdh7uNwHTs0mJn1OjIo7OrgjDvDuc/gIAQ1iHipxNGidnCbfcN6e080U0tFBEFwKc8uZ433yn6AK+8iEi6Zmn61mI4oODmpTn6Q/l/yy/4U7DNZTyydkzGOdOTPXrlrPO8Hoko2Oa0ZXv9ew7vcIrOM69FAmaQpmMpnCXhS23H1Bsj80cM8lwFdgRo7NP/6BfwTi5E07oAcdPvbJ9GXc2vov0=
  email: false
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.24.1
  - IMAGE_NAME=pkpslotex/slotex-nlp-web
addons:
  sonarcloud:
    organization: mediusinc
services:
  - docker

before_install:
  - if [ ! -f "$HOME/bin/docker-compose" ]; then curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > $HOME/bin/docker-compose; fi
  - chmod +x $HOME/bin/docker-compose
  - export PATH=$HOME/bin:$PATH
  - docker-compose version
before_script:
  - export PATH=$HOME/bin:$PATH
  - "./run-in-docker.sh --ittest"
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mvn clean verify -P sonar -Dsonar.login=$SONAR_TOKEN
  - "./run-in-docker.sh --ittest --down"

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_COMMIT; fi`
  - mvn compile jib:dockerBuild
  - if [ "$TRAVIS_TAG" != "" ]; then TAG=$TRAVIS_TAG; fi
  - if [ "$TAG" != "$TRAVIS_COMMIT" ]; then docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG; ./.travis/update-readme.sh; fi
  - docker push $IMAGE_NAME:$TAG

